server:
  port: "${SOA_SERVICE_PORT}"
  ssl:
    key-store-type: "PKCS12"
    key-store: "${KEY_STORE}"
    key-store-password: "${KEY_STORE_PASSWORD}"
    key-alias: "${KEY_ALIAS}"

    trust-store-type: "PKCS12"
    trust-store: "${TRUST_STORE}"
    trust-store-password: "${TRUST_STORE_PASSWORD}"

spring:
  main:
    banner-mode: "off"

proxy:
  target-service:
    url: "${SOA_TARGET_SERVICE_URL}"

